name: "Multievent pipeline /workflow"
on:
    push:
        branches: 
            - main
    pull_request:
        branches:
            - main
        types:
            - closed
            - opened

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "running on main push"
              run: echo "running on main branch"
    on-pull-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "running on pull request opened"
              run: echo "pull request opened"